version: '3.8'

services:
  na3-auth:
    image: na3-auth
    restart: always
    build: .
    ports:
      - '127.0.0.1:8386:${PORT:-8386}'
    volumes:
      - ./config:/go/config
    networks:
      - na3_network

networks:
  na3_network:
    external: true